#!/bin/bash

#
# portOpen - 08/31/2015
#
if [ $# -ne 2 ];then
   echo "Usage: $0 host port-number"
   exit 0
fi

IPADDR=$1
PORTNUM=$2
if [ $(echo x$PORTNUM | tr -d '[0-9]') != "x" ];then
   echo "$PORTNUM is not a valid port number"
   echo "Usage: $0 host port-number"
   exit 0
fi

:</dev/tcp/$IPADDR/$PORTNUM &>/dev/null 2>&1 && echo "OPEN" || echo "CLOSED"
